added files for templates
knoldus/Docker_with_Jenkins_and_Dagger pull request #1
Opened 2022-05-10 02:20 UTC by vaibhavkumar779

I have created a template for dagger with jenkins

2022-05-10 16:23 UTC, official-himanshu requested changes

2022-05-10 16:23 UTC, official-himanshu commented on main.cue
> +        steps: [
add more steps like installing and configuring nginx server

2022-05-11 02:40 UTC, vaibhavkumar779 commented
added requested changes in main.cue file

2022-05-11 04:50 UTC, official-himanshu approved these changes

2022-05-11 04:59 UTC, merged